---
kind: pipeline
name: build_gallery

platform:
  os: linux
  arch: amd64

workspace:
  base: /workspace
  path: src

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags

  - name: build web
    pull: if-not-exists
    image: docker
    commands:
      - /bin/sh -c "apk update && apk add bash jq git"
      - /bin/bash _ops/ci.build.sh web
    environment:
      DEBUG:
        from_secret: DEBUG
      WAIT_ON_ERROR: true
      SECRETS_B64_DEV:
        from_secret: SECRETS_B64_DEV
      SECRETS_B64_PROD:
        from_secret: SECRETS_B64_PROD
    volumes:
      - name: docksock
        path: /var/run/docker.sock
    depends_on:
      - fetch

  - name: build android
    pull: if-not-exists
    image: docker
    commands:
      - /bin/sh -c "apk update && apk add bash jq git"
      - >
        /bin/bash -c '
          if [[ "$DRONE_COMMIT_REF" == "refs/heads/master" || "$DRONE_COMMIT_REF" == "refs/heads/main" || "$DRONE_COMMIT_REF" == "refs/heads/hotfix/"* ]] &&
            [[ "$(git describe --tags --exact-match HEAD)" != "mobile/"* && "$(git describe --tags --exact-match HEAD)" != "android/"* ]]; then
            echo "Skipping build without tag."
            exit 0
          else
            /bin/bash _ops/ci.build.sh android
          fi
        '
    environment:
      DEBUG:
        from_secret: DEBUG
      WAIT_ON_ERROR: true
      SECRETS_B64_DEV:
        from_secret: SECRETS_B64_DEV
      SECRETS_B64_PROD:
        from_secret: SECRETS_B64_PROD
    volumes:
      - name: docksock
        path: /var/run/docker.sock
    when:
      ref:
        - refs/heads/main
        - refs/heads/master
        - refs/heads/hotfix/*
        - refs/tags/mobile/*
        - refs/tags/android/*
    depends_on:
      - fetch

volumes:
  - name: docksock
    host:
      path: /var/run/docker.sock

trigger:
  ref:
    - refs/heads/**
    - refs/tags/**
    - refs/pull/**
  branch:
    - main
    - master
    - hotfix/*
